[package]
name = "kit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
chrono = "0.4.27"
mysql = "24.0.0"
encoding_rs = "0.8.26"
bevy_framepace = "0.13"
